/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/screen/Playlist`; params?: Router.UnknownInputParams; } | { pathname: `/screen/Registration`; params?: Router.UnknownInputParams; } | { pathname: `/screen/Signup`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/App`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/ComponentShowcase`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/explore`; params?: Router.UnknownInputParams; } | { pathname: `/tabs`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/screen/Playlist`; params?: Router.UnknownOutputParams; } | { pathname: `/screen/Registration`; params?: Router.UnknownOutputParams; } | { pathname: `/screen/Signup`; params?: Router.UnknownOutputParams; } | { pathname: `/tabs/App`; params?: Router.UnknownOutputParams; } | { pathname: `/tabs/ComponentShowcase`; params?: Router.UnknownOutputParams; } | { pathname: `/tabs/explore`; params?: Router.UnknownOutputParams; } | { pathname: `/tabs`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/screen/Playlist${`?${string}` | `#${string}` | ''}` | `/screen/Registration${`?${string}` | `#${string}` | ''}` | `/screen/Signup${`?${string}` | `#${string}` | ''}` | `/tabs/App${`?${string}` | `#${string}` | ''}` | `/tabs/ComponentShowcase${`?${string}` | `#${string}` | ''}` | `/tabs/explore${`?${string}` | `#${string}` | ''}` | `/tabs${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/screen/Playlist`; params?: Router.UnknownInputParams; } | { pathname: `/screen/Registration`; params?: Router.UnknownInputParams; } | { pathname: `/screen/Signup`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/App`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/ComponentShowcase`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/explore`; params?: Router.UnknownInputParams; } | { pathname: `/tabs`; params?: Router.UnknownInputParams; };
    }
  }
}
